"""add thread replies pins and reactions

Revision ID: 94efb600472f
Revises: 
Create Date: 2026-05-18 21:02:59.686119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94efb600472f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('awarded_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_badges_category'), ['category'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('client_temp_id', sa.String(length=300), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by_sender', sa.Boolean(), nullable=True),
    sa.Column('deleted_by_receiver', sa.Boolean(), nullable=True),
    sa.Column('parent_message_id', sa.Integer(), nullable=True),
    sa.Column('has_thread', sa.Boolean(), nullable=True),
    sa.Column('thread_reply_count', sa.Integer(), nullable=True),
    sa.Column('related_post_id', sa.Integer(), nullable=True),
    sa.Column('related_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['related_session_id'], ['study_session_calendar.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_parent_message_id'), ['parent_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sent_at'), ['sent_at'], unique=False)

    op.create_table('study_session_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('proposed_times', sa.JSON(), nullable=True),
    sa.Column('confirmed_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('requester_notes', sa.Text(), nullable=True),
    sa.Column('requester_resources', sa.JSON(), nullable=True),
    sa.Column('receiver_notes', sa.Text(), nullable=True),
    sa.Column('receiver_resources', sa.JSON(), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('reminder_15min_sent', sa.Boolean(), nullable=True),
    sa.Column('reminder_1hour_sent', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('in_study_session', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('pin', sa.String(length=200), nullable=False),
    sa.Column('fcm_token', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('reputation', sa.Integer(), nullable=True),
    sa.Column('reputation_level', sa.String(length=20), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('login_streak', sa.Integer(), nullable=True),
    sa.Column('total_posts', sa.Integer(), nullable=True),
    sa.Column('total_helpful', sa.Integer(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('learning_goals', sa.JSON(), nullable=True),
    sa.Column('study_schedule', sa.JSON(), nullable=True),
    sa.Column('privacy_settings', sa.JSON(), nullable=True),
    sa.Column('notification_settings', sa.JSON(), nullable=True),
    sa.Column('connection_settings', sa.JSON(), nullable=True),
    sa.Column('help_streak_current', sa.Integer(), nullable=False),
    sa.Column('help_streak_longest', sa.Integer(), nullable=False),
    sa.Column('help_streak_last_updated', sa.DateTime(), nullable=True),
    sa.Column('help_streak_frozen', sa.Boolean(), nullable=False),
    sa.Column('total_helps_given', sa.Integer(), nullable=False),
    sa.Column('total_helps_received', sa.Integer(), nullable=False),
    sa.Column('first_responder_count', sa.Integer(), nullable=False),
    sa.Column('weekly_helps_count', sa.Integer(), nullable=False),
    sa.Column('weekly_helps_last_reset', sa.Date(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('bookmark_folders', sa.JSON(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_reputation'), ['reputation'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('activity_feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_feed', schema=None) as batch_op:
        batch_op.create_index('idx_activity_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_activity_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('idx_activity_type', ['activity_type'], unique=False)
        batch_op.create_index('idx_activity_user_id', ['user_id'], unique=False)

    op.create_table('ai_usage_quotas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('daily_messages_limit', sa.Integer(), nullable=True),
    sa.Column('daily_messages_used', sa.Integer(), nullable=True),
    sa.Column('last_reset_date', sa.Date(), nullable=True),
    sa.Column('last_message_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('is_shared_for_help', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_is_shared_for_help'), ['is_shared_for_help'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_subject'), ['subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignments_user_id'), ['user_id'], unique=False)

    op.create_table('bookmark_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('bookmark_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='unique_folder_per_user')
    )
    with op.batch_alter_table('bookmark_folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmark_folders_user_id'), ['user_id'], unique=False)

    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('is_seen', sa.Boolean(), nullable=True),
    sa.Column('connection_type', sa.String(length=30), nullable=True),
    sa.Column('requester_notes', sa.Text(), nullable=True),
    sa.Column('receiver_notes', sa.Text(), nullable=True),
    sa.CheckConstraint('requester_id != receiver_id', name='no_self_connection'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'receiver_id', name='unique_connection')
    )
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connections_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connections_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connections_status'), ['status'], unique=False)

    op.create_table('conversation_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_key', sa.String(length=100), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('messages_this_week', sa.Integer(), nullable=True),
    sa.Column('messages_last_week', sa.Integer(), nullable=True),
    sa.Column('subjects_discussed', sa.JSON(), nullable=True),
    sa.Column('top_subjects', sa.JSON(), nullable=True),
    sa.Column('first_message_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('most_active_day', sa.String(length=20), nullable=True),
    sa.Column('most_active_hour', sa.Integer(), nullable=True),
    sa.Column('total_study_sessions', sa.Integer(), nullable=True),
    sa.Column('total_study_time_hours', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('learning_score', sa.Float(), nullable=True),
    sa.Column('avg_response_time_minutes', sa.Float(), nullable=True),
    sa.Column('last_computed_at', sa.DateTime(), nullable=True),
    sa.Column('needs_recompute', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_key')
    )
    op.create_table('help_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('broadcast_sent', sa.Boolean(), nullable=True),
    sa.Column('volunteers', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('help_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_help_requests_requester_id'), ['requester_id'], unique=False)

    op.create_table('leaderboard_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=20), nullable=False),
    sa.Column('global_rank', sa.Integer(), nullable=True),
    sa.Column('department_rank', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leaderboard_snapshots', schema=None) as batch_op:
        batch_op.create_index('idx_lb_snap_rank', ['global_rank'], unique=False)
        batch_op.create_index('idx_lb_snap_type_date', ['snapshot_type', 'created_at'], unique=False)
        batch_op.create_index('idx_lb_snap_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_lb_snap_user_type_date', ['user_id', 'snapshot_type', 'created_at'], unique=False)

    op.create_table('live_study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('user1_timer_state', sa.JSON(), nullable=True),
    sa.Column('user2_timer_state', sa.JSON(), nullable=True),
    sa.Column('notepad_content', sa.Text(), nullable=True),
    sa.Column('notepad_version', sa.Integer(), nullable=True),
    sa.Column('last_notepad_edit_by', sa.Integer(), nullable=True),
    sa.Column('last_notepad_edit_at', sa.DateTime(), nullable=True),
    sa.Column('timer_started_at', sa.DateTime(), nullable=True),
    sa.Column('timer_paused_at', sa.DateTime(), nullable=True),
    sa.Column('timer_total_seconds', sa.Integer(), nullable=True),
    sa.Column('timer_is_running', sa.Boolean(), nullable=True),
    sa.Column('timer_owner_id', sa.Integer(), nullable=True),
    sa.Column('ai_messages', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('session_log', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('topics_covered', sa.JSON(), nullable=True),
    sa.Column('problems_solved', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_notepad_edit_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['timer_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_key')
    )
    op.create_table('mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentioned_in_type', sa.String(length=20), nullable=False),
    sa.Column('mentioned_in_id', sa.Integer(), nullable=False),
    sa.Column('mentioned_user_id', sa.Integer(), nullable=False),
    sa.Column('mentioned_by_user_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('mentioned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mentioned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mentions_mentioned_in_id'), ['mentioned_in_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mentions_mentioned_in_type'), ['mentioned_in_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_mentions_mentioned_user_id'), ['mentioned_user_id'], unique=False)

    op.create_table('message_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reaction_type', sa.String(length=50), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('reacted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='unique_user_reaction')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('related_type', sa.String(length=20), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('onboarding_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('class_level', sa.String(length=20), nullable=True),
    sa.Column('subjects', sa.JSON(), nullable=True),
    sa.Column('learning_style', sa.String(length=300), nullable=True),
    sa.Column('study_preferences', sa.JSON(), nullable=True),
    sa.Column('help_subjects', sa.JSON(), nullable=True),
    sa.Column('strong_subjects', sa.JSON(), nullable=True),
    sa.Column('study_schedule', sa.JSON(), nullable=True),
    sa.Column('session_length', sa.String(length=100), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('peer_teaching_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('teaching_type', sa.String(length=50), nullable=True),
    sa.Column('sessions_completed', sa.Integer(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('topics_covered', sa.JSON(), nullable=True),
    sa.Column('initial_skill_level', sa.Integer(), nullable=True),
    sa.Column('current_skill_level', sa.Integer(), nullable=True),
    sa.Column('skill_improvement', sa.Float(), nullable=True),
    sa.Column('learner_rating', sa.Float(), nullable=True),
    sa.Column('teacher_rating', sa.Float(), nullable=True),
    sa.Column('learner_feedback', sa.Text(), nullable=True),
    sa.Column('teacher_feedback', sa.Text(), nullable=True),
    sa.Column('resources_shared', sa.JSON(), nullable=True),
    sa.Column('problems_solved_together', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('learning_goals', sa.JSON(), nullable=True),
    sa.Column('goals_achieved', sa.JSON(), nullable=True),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_session_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('learner_rating >= 1 AND learner_rating <= 5', name='check_learner_rating'),
    sa.CheckConstraint('teacher_id != learner_id', name='check_different_users'),
    sa.CheckConstraint('teacher_rating >= 1 AND teacher_rating <= 5', name='check_teacher_rating'),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('post_type', sa.String(length=50), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('positive_reactions_count', sa.Integer(), nullable=True),
    sa.Column('dislikes_count', sa.Integer(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('bookmark_count', sa.Integer(), nullable=True),
    sa.Column('helpful_reactions_count', sa.Integer(), nullable=True),
    sa.Column('thread_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_solved', sa.Boolean(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('solved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_post_type'), ['post_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_posted_at'), ['posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_posts_student_id'), ['student_id'], unique=False)

    op.create_table('profile_change_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('field_changed', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.String(length=500), nullable=True),
    sa.Column('new_value', sa.String(length=500), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_change_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_change_history_change_type'), ['change_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_change_history_user_id'), ['user_id'], unique=False)

    op.create_table('reputation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('points_change', sa.Integer(), nullable=False),
    sa.Column('related_type', sa.String(length=20), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reputation_before', sa.Integer(), nullable=True),
    sa.Column('reputation_after', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reputation_history', schema=None) as batch_op:
        batch_op.create_index('idx_rep_history_date_user', ['created_at', 'user_id'], unique=False)
        batch_op.create_index('idx_rep_history_user_date', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reputation_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reputation_history_user_id'), ['user_id'], unique=False)

    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pin', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('guardian_name', sa.String(length=120), nullable=True),
    sa.Column('guardian_contact', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.create_index('idx_student_profiles_dept_user', ['department', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profiles_username'), ['username'], unique=True)

    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('posts_created', sa.Integer(), nullable=True),
    sa.Column('comments_created', sa.Integer(), nullable=True),
    sa.Column('threads_joined', sa.Integer(), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('activity_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'activity_date', name='unique_daily_activity')
    )
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.create_index('idx_user_activity_user_date_score', ['user_id', 'activity_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_activity_date'), ['activity_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_user_id'), ['user_id'], unique=False)

    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='unique_user_badge')
    )
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_badges_badge_id'), ['badge_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_badges_user_id'), ['user_id'], unique=False)

    op.create_table('user_warnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.Column('related_type', sa.String(length=20), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_warnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_warnings_user_id'), ['user_id'], unique=False)

    op.create_table('waitlist_signups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=False),
    sa.Column('referred_by', sa.String(length=20), nullable=True),
    sa.Column('referral_count', sa.Integer(), nullable=True),
    sa.Column('waitlist_position', sa.Integer(), nullable=True),
    sa.Column('signup_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('referral_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('weekly_champions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('help_count', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('avg_response_time_minutes', sa.String(length=50), nullable=True),
    sa.Column('champion_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_champions', schema=None) as batch_op:
        batch_op.create_index('idx_champion_subject', ['subject'], unique=False)
        batch_op.create_index('idx_champion_type', ['champion_type'], unique=False)
        batch_op.create_index('idx_champion_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_champion_week', ['week_start', 'week_end'], unique=False)

    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('folder', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('bookmarked_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['bookmark_folders.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'student_id', name='unique_bookmark')
    )
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookmarks_folder'), ['folder'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookmarks_folder_id'), ['folder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookmarks_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookmarks_student_id'), ['student_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('replies_count', sa.Integer(), nullable=True),
    sa.Column('depth_level', sa.Integer(), nullable=True),
    sa.Column('is_solution', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_depth_level'), ['depth_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_post_id'), ['post_id'], unique=False)

    op.create_table('homework_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('helper_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('solution_text', sa.Text(), nullable=True),
    sa.Column('solution_resources', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('feedback_resources', sa.JSON(), nullable=True),
    sa.Column('feedback_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reaction_type', sa.String(length=50), nullable=True),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('reaction_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_marked_helpful', sa.Boolean(), nullable=True),
    sa.Column('study_session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['helper_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['study_session_id'], ['live_study_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('homework_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_homework_submissions_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_homework_submissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_homework_submissions_helper_id'), ['helper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_homework_submissions_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_homework_submissions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_homework_submissions_subject'), ['subject'], unique=False)

    op.create_table('post_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('awarded_badge_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['awarded_badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'event_type', name='unique_post_event')
    )
    with op.batch_alter_table('post_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_events_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_events_processed'), ['processed'], unique=False)

    op.create_table('post_follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('followed_at', sa.DateTime(), nullable=True),
    sa.Column('notify_on_comment', sa.Boolean(), nullable=True),
    sa.Column('notify_on_solution', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'student_id', name='unique_post_follow')
    )
    with op.batch_alter_table('post_follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_follows_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_follows_student_id'), ['student_id'], unique=False)

    op.create_table('post_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('reaction_type', sa.String(length=20), nullable=False),
    sa.Column('reacted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'student_id', name='unique_post_reaction')
    )
    with op.batch_alter_table('post_reactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_reactions_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_reactions_student_id'), ['student_id'], unique=False)

    op.create_table('post_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_reports_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_reports_reported_by'), ['reported_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_reports_status'), ['status'], unique=False)

    op.create_table('post_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', 'viewed_at', name='unique_daily_view')
    )
    with op.batch_alter_table('post_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_views_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_views_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_views_viewed_at'), ['viewed_at'], unique=False)

    op.create_table('search_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('searchable_text', sa.Text(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('post_type', sa.String(length=50), nullable=True),
    sa.Column('tags_text', sa.String(length=500), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_index_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_post_id'), ['post_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_search_index_post_type'), ['post_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_index_tags_text'), ['tags_text'], unique=False)

    op.create_table('threads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar', sa.String(length=300), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threads_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_threads_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_threads_post_id'), ['post_id'], unique=False)

    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('attachment', sa.String(length=200), nullable=True),
    sa.Column('related_post_id', sa.Integer(), nullable=True),
    sa.Column('related_comment_id', sa.Integer(), nullable=True),
    sa.Column('last_incomplete_message', sa.Text(), nullable=True),
    sa.Column('is_last_message_complete', sa.Boolean(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['related_post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_helpful_marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('marked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='unique_helpful_mark')
    )
    with op.batch_alter_table('comment_helpful_marks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_helpful_marks_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_helpful_marks_user_id'), ['user_id'], unique=False)

    op.create_table('comment_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('liked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'student_id', name='unique_comment_like')
    )
    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_likes_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_likes_student_id'), ['student_id'], unique=False)

    op.create_table('study_buddy_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('subjects', sa.JSON(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('sessions_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user1_id', 'user2_id', name='unique_study_match')
    )
    with op.batch_alter_table('study_buddy_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_buddy_matches_user1_id'), ['user1_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_buddy_matches_user2_id'), ['user2_id'], unique=False)

    op.create_table('study_buddy_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('subjects', sa.JSON(), nullable=True),
    sa.Column('availability', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'receiver_id', name='unique_study_buddy_request')
    )
    with op.batch_alter_table('study_buddy_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_buddy_requests_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_buddy_requests_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_buddy_requests_status'), ['status'], unique=False)

    op.create_table('thread_join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'requester_id', name='unique_join_request')
    )
    with op.batch_alter_table('thread_join_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thread_join_requests_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_join_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_join_requests_thread_id'), ['thread_id'], unique=False)

    op.create_table('thread_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.Column('messages_sent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'student_id', name='unique_thread_member')
    )
    with op.batch_alter_table('thread_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thread_members_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_members_thread_id'), ['thread_id'], unique=False)

    op.create_table('thread_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('attachment_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_type', sa.String(length=50), nullable=True),
    sa.Column('attachment_size', sa.Integer(), nullable=True),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('pinned_by_id', sa.Integer(), nullable=True),
    sa.Column('is_ai_response', sa.Boolean(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pinned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reply_to_id'], ['thread_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thread_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thread_messages_reply_to_id'), ['reply_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_messages_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_messages_thread_id'), ['thread_id'], unique=False)

    op.create_table('thread_message_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('reacted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['thread_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='unique_thread_msg_reaction')
    )
    with op.batch_alter_table('thread_message_reactions', schema=None) as batch_op:
        batch_op.create_index('idx_thread_rxn_message', ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_message_reactions_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_message_reactions_user_id'), ['user_id'], unique=False)

    op.create_table('thread_message_read_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['thread_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='unique_thread_read_receipt')
    )
    with op.batch_alter_table('thread_message_read_receipts', schema=None) as batch_op:
        batch_op.create_index('idx_tread_receipt_msg', ['message_id'], unique=False)
        batch_op.create_index('idx_tread_receipt_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_message_read_receipts_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_message_read_receipts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread_message_read_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thread_message_read_receipts_user_id'))
        batch_op.drop_index(batch_op.f('ix_thread_message_read_receipts_message_id'))
        batch_op.drop_index('idx_tread_receipt_user')
        batch_op.drop_index('idx_tread_receipt_msg')

    op.drop_table('thread_message_read_receipts')
    with op.batch_alter_table('thread_message_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thread_message_reactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_thread_message_reactions_message_id'))
        batch_op.drop_index('idx_thread_rxn_message')

    op.drop_table('thread_message_reactions')
    with op.batch_alter_table('thread_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thread_messages_thread_id'))
        batch_op.drop_index(batch_op.f('ix_thread_messages_sent_at'))
        batch_op.drop_index(batch_op.f('ix_thread_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_thread_messages_reply_to_id'))

    op.drop_table('thread_messages')
    with op.batch_alter_table('thread_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thread_members_thread_id'))
        batch_op.drop_index(batch_op.f('ix_thread_members_student_id'))

    op.drop_table('thread_members')
    with op.batch_alter_table('thread_join_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thread_join_requests_thread_id'))
        batch_op.drop_index(batch_op.f('ix_thread_join_requests_status'))
        batch_op.drop_index(batch_op.f('ix_thread_join_requests_requester_id'))

    op.drop_table('thread_join_requests')
    with op.batch_alter_table('study_buddy_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_buddy_requests_status'))
        batch_op.drop_index(batch_op.f('ix_study_buddy_requests_requester_id'))
        batch_op.drop_index(batch_op.f('ix_study_buddy_requests_receiver_id'))

    op.drop_table('study_buddy_requests')
    with op.batch_alter_table('study_buddy_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_buddy_matches_user2_id'))
        batch_op.drop_index(batch_op.f('ix_study_buddy_matches_user1_id'))

    op.drop_table('study_buddy_matches')
    with op.batch_alter_table('comment_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_likes_student_id'))
        batch_op.drop_index(batch_op.f('ix_comment_likes_comment_id'))

    op.drop_table('comment_likes')
    with op.batch_alter_table('comment_helpful_marks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_helpful_marks_user_id'))
        batch_op.drop_index(batch_op.f('ix_comment_helpful_marks_comment_id'))

    op.drop_table('comment_helpful_marks')
    op.drop_table('ai_conversations')
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threads_post_id'))
        batch_op.drop_index(batch_op.f('ix_threads_department'))
        batch_op.drop_index(batch_op.f('ix_threads_creator_id'))

    op.drop_table('threads')
    with op.batch_alter_table('search_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_index_tags_text'))
        batch_op.drop_index(batch_op.f('ix_search_index_post_type'))
        batch_op.drop_index(batch_op.f('ix_search_index_post_id'))
        batch_op.drop_index(batch_op.f('ix_search_index_department'))

    op.drop_table('search_index')
    with op.batch_alter_table('post_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_views_viewed_at'))
        batch_op.drop_index(batch_op.f('ix_post_views_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_views_post_id'))

    op.drop_table('post_views')
    with op.batch_alter_table('post_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_reports_status'))
        batch_op.drop_index(batch_op.f('ix_post_reports_reported_by'))
        batch_op.drop_index(batch_op.f('ix_post_reports_post_id'))

    op.drop_table('post_reports')
    with op.batch_alter_table('post_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_reactions_student_id'))
        batch_op.drop_index(batch_op.f('ix_post_reactions_post_id'))

    op.drop_table('post_reactions')
    with op.batch_alter_table('post_follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_follows_student_id'))
        batch_op.drop_index(batch_op.f('ix_post_follows_post_id'))

    op.drop_table('post_follows')
    with op.batch_alter_table('post_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_events_processed'))
        batch_op.drop_index(batch_op.f('ix_post_events_post_id'))
        batch_op.drop_index(batch_op.f('ix_post_events_event_type'))

    op.drop_table('post_events')
    with op.batch_alter_table('homework_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_homework_submissions_subject'))
        batch_op.drop_index(batch_op.f('ix_homework_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_homework_submissions_requester_id'))
        batch_op.drop_index(batch_op.f('ix_homework_submissions_helper_id'))
        batch_op.drop_index(batch_op.f('ix_homework_submissions_created_at'))
        batch_op.drop_index(batch_op.f('ix_homework_submissions_assignment_id'))

    op.drop_table('homework_submissions')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_comments_depth_level'))

    op.drop_table('comments')
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmarks_student_id'))
        batch_op.drop_index(batch_op.f('ix_bookmarks_post_id'))
        batch_op.drop_index(batch_op.f('ix_bookmarks_folder_id'))
        batch_op.drop_index(batch_op.f('ix_bookmarks_folder'))

    op.drop_table('bookmarks')
    with op.batch_alter_table('weekly_champions', schema=None) as batch_op:
        batch_op.drop_index('idx_champion_week')
        batch_op.drop_index('idx_champion_user_id')
        batch_op.drop_index('idx_champion_type')
        batch_op.drop_index('idx_champion_subject')

    op.drop_table('weekly_champions')
    op.drop_table('waitlist_signups')
    with op.batch_alter_table('user_warnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_warnings_user_id'))

    op.drop_table('user_warnings')
    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_badges_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_badges_badge_id'))

    op.drop_table('user_badges')
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activity_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_activity_activity_date'))
        batch_op.drop_index('idx_user_activity_user_date_score')

    op.drop_table('user_activity')
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profiles_username'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_department'))
        batch_op.drop_index(batch_op.f('ix_student_profiles_class_name'))
        batch_op.drop_index('idx_student_profiles_dept_user')

    op.drop_table('student_profiles')
    with op.batch_alter_table('reputation_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reputation_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_reputation_history_created_at'))
        batch_op.drop_index('idx_rep_history_user_date')
        batch_op.drop_index('idx_rep_history_date_user')

    op.drop_table('reputation_history')
    with op.batch_alter_table('profile_change_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_change_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_profile_change_history_change_type'))

    op.drop_table('profile_change_history')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_student_id'))
        batch_op.drop_index(batch_op.f('ix_posts_posted_at'))
        batch_op.drop_index(batch_op.f('ix_posts_post_type'))
        batch_op.drop_index(batch_op.f('ix_posts_department'))

    op.drop_table('posts')
    op.drop_table('peer_teaching_relationships')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))

    op.drop_table('password_reset_tokens')
    op.drop_table('onboarding_details')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    op.drop_table('message_reactions')
    with op.batch_alter_table('mentions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mentions_mentioned_user_id'))
        batch_op.drop_index(batch_op.f('ix_mentions_mentioned_in_type'))
        batch_op.drop_index(batch_op.f('ix_mentions_mentioned_in_id'))

    op.drop_table('mentions')
    op.drop_table('live_study_sessions')
    with op.batch_alter_table('leaderboard_snapshots', schema=None) as batch_op:
        batch_op.drop_index('idx_lb_snap_user_type_date')
        batch_op.drop_index('idx_lb_snap_user_id')
        batch_op.drop_index('idx_lb_snap_type_date')
        batch_op.drop_index('idx_lb_snap_rank')

    op.drop_table('leaderboard_snapshots')
    with op.batch_alter_table('help_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_help_requests_requester_id'))

    op.drop_table('help_requests')
    op.drop_table('conversation_analytics')
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connections_status'))
        batch_op.drop_index(batch_op.f('ix_connections_requester_id'))
        batch_op.drop_index(batch_op.f('ix_connections_receiver_id'))

    op.drop_table('connections')
    with op.batch_alter_table('bookmark_folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookmark_folders_user_id'))

    op.drop_table('bookmark_folders')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_assignments_subject'))
        batch_op.drop_index(batch_op.f('ix_assignments_status'))
        batch_op.drop_index(batch_op.f('ix_assignments_is_shared_for_help'))
        batch_op.drop_index(batch_op.f('ix_assignments_due_date'))

    op.drop_table('assignments')
    op.drop_table('ai_usage_quotas')
    with op.batch_alter_table('activity_feed', schema=None) as batch_op:
        batch_op.drop_index('idx_activity_user_id')
        batch_op.drop_index('idx_activity_type')
        batch_op.drop_index('idx_activity_expires_at')
        batch_op.drop_index('idx_activity_created_at')

    op.drop_table('activity_feed')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_reputation'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('study_session_calendar')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sent_at'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_messages_parent_message_id'))
        batch_op.drop_index(batch_op.f('ix_messages_is_read'))
        batch_op.drop_index(batch_op.f('ix_messages_is_deleted'))

    op.drop_table('messages')
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_badges_category'))

    op.drop_table('badges')
    # ### end Alembic commands ###
